### ISSUE TITLE
Outlandish funding for "open source projects with social impact"

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/funding#5]
Hi all,

I saw Outlandish mentioned on a mailing list I'm on. They are a funding org that fund projects with social impact. 
## From their website:

Outlandish is making fellowships available for people who are using the Internet and digital technologies to address social issues. The fellowships include funding and other forms of support to allow participants to start their own projects.

The aim of the fellowship is to support work that matches the mission of Outlandish, and to expand the network of people that we actively collaborate with. The ideal candidates for the fellowship are working on interesting and socially relevant problems, and would also benefit from the expertise and connections that Outlandish has.

We are organising a launch event on March 15th. It will be an opportunity for everybody interested in the fellowship to ask questions and discuss their ideas informally. As we hope to run the application process in a way that is focused more on interaction than paperwork, we encourage everybody interested in the fellowship to attend.

What would it be like to be a fellow?
- Fellows receive financial support allowing them to work part-time or full-time on their ideas. We have the chance to give 10 fellowships of £5,000 and 2 larger fellowships of up to £25,000.
- Fellows will develop their own project related to technology and social change (see below for our focus). The output could be, for instance, a prototype or MVP for a digital service or a piece of open source software.

---

More here: http://www.outlandish.com/fellowship/

Hope this is interesting.

Bernard

**Comment by simonv3** [comment]
Thanks for the share @ei8fdb!

**Comment by bnvk** [comment]
I've ported this information out to [organization repo](https://github.com/opensourcedesign/organization/) now!
