### ISSUE TITLE
How to post funding opportunities?

### ISSUE THREAD

**Issue by joncamfield** [opensourcedesign/funding#6]
The /funding repo seems more focused on a meta-discussion of funding types and their benefits. Might it also take a similar approach to /events and /jobs, and also support listing of currently open funding opportunities to capture information such as #5 (and the upcoming UXFund) ?

**Comment by simonv3** [comment]
@joncamfield That is probably an excellent idea. 

Anyone interested in implementing it?

**Comment by joncamfield** [comment]
I've lost all my free time since I made this request - the UXFund has come and almost gone - it's been extended through Sep 30 (https://usable.tools/uxfund).  For now, I'll fork and add in-line text with some current resources.

**Comment by bnvk** [comment]
I've ported this information out to [organization repo](https://github.com/opensourcedesign/organization/) now!
